name: Bug Report
description: Report a bug in ztlctl
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the form below.

  - type: input
    id: version
    attributes:
      label: ztlctl version
      description: Output of `ztlctl --version`
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Output of `python --version`
      placeholder: "3.13.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error output if applicable.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: >
        Any additional context (ztlctl.toml config, vault structure, etc.).
        Use `ztlctl check --json` output if relevant.
    validations:
      required: false
